CREATE ROLE DEV_ROLE;

GRANT ROLE DEV_ROLE TO USER KOMI21;

CREATE DATABASE DEV_DB;

GRANT USAGE ON DATABASE DEV_DB TO ROLE DEV_ROLE;

GRANT USAGE ON SCHEMA PUBLIC TO ROLE DEV_ROLE;

GRANT CREATE TABLE ON SCHEMA PUBLIC TO DEV_ROLE;


----> WAS NOT ABLE TO CREATE TABLE, SO GRANTED THE CREATE ACCESS
GRANT CREATE TABLE ON SCHEMA DEV_DB.PUBLIC TO ROLE DEV_ROLE;

---> RUN THIS BELOW QUERY INTO OTHER WORKSEET UNDER DEV ROLE TO CHECK WHETER THE GRANTS ARE WORKING OR NOT
CREATE TABLE DEV_TABLE(
A NUMBER
);
