CREATE SCHEMA DATA_STREAMS;
USE SCHEMA DATA_STREAMS;

CREATE OR REPLACE TABLE EMPLOYEE_RAW(ID NUMBER, NAME STRING, SALARY NUMBER);

---INSERT
INSERT INTO EMPLOYEE_RAW VALUES (101,'TONY', 25000);
INSERT INTO EMPLOYEE_RAW VALUES (102,'CHRIS', 30000);
INSERT INTO EMPLOYEE_RAW VALUES (103,'BRUCE', 35000);

SELECT * FROM EMPLOYEE_RAW;

CREATE OR REPLACE TABLE EMPLOYEES(ID NUMBER, NAME STRING, SALARY NUMBER);

INSERT INTO EMPLOYEES SELECT * FROM EMPLOYEE_RAW;

SELECT * FROM EMPLOYEES;


---> CREATE A STREAM 
CREATE OR REPLACE STREAM EMP_STREAM ON TABLE EMPLOYEE_RAW;

SHOW STREAMS;

SELECT * FROM EMP_STREAM;

---DML OPERATIONS
---Insert new record
INSERT INTO EMPLOYEE_RAW VALUES (104,'KOMAL', 55000);
---update old records
UPDATE EMPLOYEE_RAW SET SALARY= '10000' WHERE ID=102;
---Delete one record
DELETE FROM EMPLOYEE_RAW WHERE ID=104;

--- Only fetching the INSERT data from stream
SELECT * FROM EMP_STREAM WHERE METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = 'FALSE';

--- Only fetching the UPDATE data
SELECT * FROM EMP_STREAM WHERE METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE = 'TRUE';

--- Only fetching the DELETE data
SELECT * FROM EMP_STREAM WHERE METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE = 'FALSE';

MERGE INTO EMPLOYEES EMP USING EMP_STREAM EMP_S ON EMP.ID=EMP_S.ID
WHEN MATCHED
AND 
METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE = 'FALSE'
THEN DELETE

WHEN MATCHED
AND
METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = 'TRUE'
THEN
UPDATE SET EMP.NAME=EMP_S.NAME, EMP.SALARY=EMP_S.SALARY

WHEN NOT MATCHED
AND
METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = 'FALSE'
THEN
INSERT(ID, NAME, SALARY) VALUES (EMP_S.ID, EMP_S.NAME, EMP_S.SALARY);


SELECT *  FROM EMPLOYEES;
