CREATE OR REPLACE TABLE EMP(
ID INT,
NAME STRING
);

---Creating a standard streams
CREATE OR REPLACE STREAM STANDARD_STREAM ON TABLE EMP;

--- creating an append-only streams
CREATE OR REPLACE STREAM APPEND_ONLY_STREAM ON TABLE EMP APPEND_ONLY=TRUE;


---INSERT
INSERT INTO EMP VALUES (101,'TONY');
INSERT INTO EMP VALUES (102,'CHRIS');
INSERT INTO EMP VALUES (103,'BRUCE');

SELECT * FROM STANDARD_STREAM;

SELECT * FROM APPEND_ONLY_STREAM;



DELETE FROM EMP WHERE ID=103;


CREATE OR REPLACE TABLE EMP_INT(
ID INT,
NAME STRING,
STREAM_TYPE STRING DEFAULT NULL
);

SELECT * FROM EMP_INT;

INSERT INTO EMP_INT(ID, NAME, STREAM_TYPE) SELECT ID, NAME, 'DELTA_STREAM' FROM STANDARD_STREAM;

TRUNCATE TABLE EMP_INT;

INSERT INTO EMP_INT(ID, NAME, STREAM_TYPE) SELECT ID, NAME, 'DELTA_STREAM' FROM APPEND_ONLY_STREAM;


SELECT * FROM STANDARD_STREAM; --No records, as the stream data are consumend from the previous offset and set to 0.


---------------------------------------------------------------------------------------------------------------
---Create the table
CREATE OR REPLACE TABLE MEMBERS (
ID INT,
NAME STRING DEFAULT NULL,
FEE INT NULL
);

---Offset created at initial level
CREATE OR REPLACE STREAM MEMBER_CHECK ON TABLE MEMBERS;

---creating the table signup
CREATE OR REPLACE TABLE SIGNUP(
ID INT,
DT_JOIN DATE
);


INSERT INTO MEMBERS (ID, NAME, FEE) VALUES(1, 'KOMAL',0),(2, 'NIKHIL',0), (3, 'RIDDHI',0),(4,'SIDDHI',0),(5, 'ASHA',0);

INSERT INTO SIGNUP VALUES
(1, '2024-01-01'),
(2, '2023-12-01'),
(3, '2023-11-30'),
(4, '2023-11-30'),
(5, '2023-11-30');

SELECT * FROM SIGNUP;


--- AFTER 30-11-2023 -> 90  DOLLARS
--- FREE FOR 1 MONTHS TO NEW MEMBERS

SELECT * FROM SIGNUP WHERE DATEDIFF(DAY,'2023-11-30'::DATE, DT_JOIN::DATE)<-30;

